### ISSUE TITLE
Customizable Ore Gen

### ISSUE THREAD

**Issue by Brickwrath** [dfsek/BetterEnd-Public#37]
Currently the configuration option(s) for Aether gen simple toggles ore gen on/off.

It would be nice to have an expanded option list to enable/disable specific ores and their generation rates.

For example:
aether:
  ores:
    enable-ores: true
    coal_ore:
      enabled: false
    iron_ore:
      enabled: true
      spawn-rate: 1000
      amount: 8
      y-min: 50
      y-max: 80
… and so on

**Comment by dfsek** [comment]
I'll most likely do something along the lines of
```yaml
ores:
    enable: true
    weights:
        iron_ore: 50
        coal_ore: 70
        #etc
```
